addons:
  chrome: stable
notifications:
  email: false
jobs:
  include:
    - stage: test-visual
      language: node_js
      git:
        depth: 3
      node_js:
        - "10"
      install:
        - bundle install --deployment --jobs=3 --retry=3 --clean
        - npm install
      before_script:
        - google-chrome-stable --product-version
      script:
        - npm run test-visual
      cache:
        directories:
          - node_modules
          - ~/.cache
